from __future__ import annotations

import argparse
import csv
import json
import sys
from collections.abc import Iterable
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from data.schemas.source_registry import (  # noqa: E402
    DatasetCandidate,
    SourceCatalog,
    dedupe_candidates,
    normalize_candidate_record,
    read_jsonl,
    validate_candidate_records,
    write_jsonl,
)

CANDIDATES_PATH = ROOT / "data" / "registry" / "dataset_candidates.jsonl"
APPROVED_PATH = ROOT / "data" / "registry" / "approved_datasets.jsonl"
RESEARCH_EVAL_PATH = ROOT / "data" / "registry" / "research_eval_datasets.jsonl"
REJECTED_PATH = ROOT / "data" / "registry" / "rejected_datasets.jsonl"
TASK_MAPPED_PATH = ROOT / "data" / "registry" / "task_mapped_datasets.jsonl"
REPORTS_DIR = ROOT / "reports"
DATASET_CARDS_DIR = ROOT / "data" / "dataset_cards"
SPLITS_DIR = ROOT / "data" / "splits"
DEFAULT_ACCESS_DATE = "2026-06-13"


def candidate(**values: object) -> DatasetCandidate:
    defaults: dict[str, object] = {
        "access_date": DEFAULT_ACCESS_DATE,
        "discovered_by": "local-lm offline seed",
        "mirror_url": None,
        "dataset_version": "unknown",
        "license_url": None,
        "contains_sensitive_data": False,
        "local_path": None,
        "checksum": None,
        "size_bytes": None,
        "metadata": {},
        "redacted": False,
        "explicit_user_opt_in": False,
        "metadata_only": True,
        "cloud_runtime_dependency": False,
        "download_approved": False,
    }
    defaults.update(values)
    return DatasetCandidate.model_validate(normalize_candidate_record(defaults))


def write_candidates(records: Iterable[DatasetCandidate], output: Path) -> None:
    write_jsonl(output, dedupe_candidates(records))


def output_arg(default: Path) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=default)
    return parser


def records_for_source(source: SourceCatalog | str) -> list[DatasetCandidate]:
    source_value = str(source)
    return [record for record in seed_records() if str(record.source_catalog) == source_value]


def filter_records(
    records: Iterable[DatasetCandidate],
    *,
    query: str = "",
    max_results: int | None = None,
) -> list[DatasetCandidate]:
    query_text = query.strip().casefold()
    filtered = []
    for record in records:
        haystack = " ".join(
            [
                record.dataset_id,
                record.dataset_name,
                record.notes,
                " ".join(str(task) for task in record.candidate_tasks),
            ]
        ).casefold()
        if query_text and query_text not in haystack:
            continue
        filtered.append(record)
        if max_results is not None and len(filtered) >= max_results:
            break
    return filtered


def load_manifest_records(path: Path, *, source_catalog: SourceCatalog) -> list[DatasetCandidate]:
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".jsonl":
        raw_records = read_jsonl(path)
    elif path.suffix.lower() == ".json":
        payload = json.loads(path.read_text(encoding="utf-8"))
        raw_records = payload.get("datasets", []) if isinstance(payload, dict) else payload
        if not isinstance(raw_records, list):
            raise ValueError("JSON manifest must be a list or contain a datasets list")
    elif path.suffix.lower() == ".csv":
        with path.open("r", encoding="utf-8", newline="") as csv_file:
            raw_records = list(csv.DictReader(csv_file))
    else:
        raise ValueError("manifest must be .json, .jsonl, or .csv")

    records = []
    for raw in raw_records:
        if not isinstance(raw, dict):
            raise ValueError("manifest records must be objects")
        payload = normalize_candidate_record(raw)
        payload["source_catalog"] = str(source_catalog)
        records.append(DatasetCandidate.model_validate(payload))
    return records


def load_candidates(path: Path) -> list[DatasetCandidate]:
    return validate_candidate_records(read_jsonl(path))


def seed_records() -> list[DatasetCandidate]:
    records = [
        # Document OCR / invoices / receipts.
        candidate(
            dataset_id="huggingface:mychen76/invoices-and-receipts_ocr_v1",
            dataset_name="mychen76 invoices-and-receipts OCR v1",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/mychen76/invoices-and-receipts_ocr_v1",
            modality="document_image",
            candidate_tasks=["invoice_extraction", "receipt_extraction", "document_ocr"],
            regions=["North America", "Europe"],
            countries=["United States", "United Kingdom"],
            languages=["en"],
            license_name="Apache-2.0",
            license_url="https://www.apache.org/licenses/LICENSE-2.0",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            contains_sensitive_data=True,
            intended_use="eval",
            source_quality="medium",
            size_bytes=1_500_000_000,
            notes="Large invoice/receipt OCR candidate; real document fields require PII review.",
            metadata={"hf_repo_id": "mychen76/invoices-and-receipts_ocr_v1"},
        ),
        candidate(
            dataset_id="huggingface:ryanznie/SROIE_2019_with_labels",
            dataset_name="SROIE 2019 with labels",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/ryanznie/SROIE_2019_with_labels",
            modality="document_image",
            candidate_tasks=["receipt_extraction", "document_ocr"],
            regions=["Southeast Asia"],
            countries=["Malaysia"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="training",
            source_quality="high",
            notes="Receipt OCR labels; useful for SROIE receipt extraction evaluation.",
            metadata={"hf_repo_id": "ryanznie/SROIE_2019_with_labels"},
        ),
        candidate(
            dataset_id="huggingface:Voxel51/scanned_receipts",
            dataset_name="Voxel51 scanned receipts",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/Voxel51/scanned_receipts",
            modality="document_image",
            candidate_tasks=["receipt_extraction", "document_ocr"],
            regions=["North America"],
            countries=["United States"],
            languages=["en"],
            license_name="Apache-2.0",
            license_url="https://www.apache.org/licenses/LICENSE-2.0",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            contains_sensitive_data=True,
            intended_use="eval",
            source_quality="medium",
            notes="Receipt image candidate; inspect real document PII before training.",
            metadata={"hf_repo_id": "Voxel51/scanned_receipts"},
        ),
        candidate(
            dataset_id="huggingface:Voxel51/consolidated_receipt_dataset",
            dataset_name="Voxel51 consolidated receipt dataset",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/Voxel51/consolidated_receipt_dataset",
            modality="document_image",
            candidate_tasks=["receipt_extraction", "document_ocr"],
            regions=["North America", "Europe"],
            countries=["United States", "Germany"],
            languages=["en", "de"],
            license_name="Apache-2.0",
            license_url="https://www.apache.org/licenses/LICENSE-2.0",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Large receipt dataset; approval required before content download.",
            size_bytes=1_200_000_000,
            metadata={"hf_repo_id": "Voxel51/consolidated_receipt_dataset"},
        ),
        candidate(
            dataset_id="huggingface:Voxel51/high-quality-invoice-images-for-ocr",
            dataset_name="Voxel51 high quality invoice images for OCR",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/Voxel51/high-quality-invoice-images-for-ocr",
            modality="document_image",
            candidate_tasks=["invoice_extraction", "document_ocr"],
            regions=["North America", "Europe"],
            countries=["United States", "United Kingdom"],
            languages=["en"],
            license_name="Apache-2.0",
            license_url="https://www.apache.org/licenses/LICENSE-2.0",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Invoice OCR image candidate; real invoices need PII review.",
            metadata={"hf_repo_id": "Voxel51/high-quality-invoice-images-for-ocr"},
        ),
        candidate(
            dataset_id="kaggle:senju14/invoice-ocr",
            dataset_name="Kaggle invoice OCR",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets/senju14/invoice-ocr",
            modality="document_image",
            candidate_tasks=["invoice_extraction", "document_ocr"],
            regions=["India", "North America"],
            countries=["India", "United States"],
            languages=["en"],
            license_name="CC-BY-SA-4.0",
            license_url="https://creativecommons.org/licenses/by-sa/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            contains_sensitive_data=True,
            intended_use="eval",
            source_quality="medium",
            notes="Kaggle metadata only; token optional for developer download.",
            metadata={"kaggle_slug": "senju14/invoice-ocr"},
        ),
        candidate(
            dataset_id="kaggle:ayoubcherguelaine/company-documents-dataset",
            dataset_name="Company documents dataset",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets/ayoubcherguelaine/company-documents-dataset",
            modality="pdf",
            candidate_tasks=["document_ocr", "text_summarization"],
            regions=["Europe", "North America"],
            countries=["France", "United States"],
            languages=["en", "fr"],
            license_name="CC0-1.0",
            license_url="https://creativecommons.org/publicdomain/zero/1.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Company document candidate; review legal/business sensitivity.",
            metadata={"kaggle_slug": "ayoubcherguelaine/company-documents-dataset"},
        ),
        candidate(
            dataset_id="kaggle:osamahosamabdellatif/high-quality-invoice-images-for-ocr",
            dataset_name="Kaggle high quality invoice images for OCR",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets/osamahosamabdellatif/high-quality-invoice-images-for-ocr",
            modality="document_image",
            candidate_tasks=["invoice_extraction", "document_ocr"],
            regions=["North America", "Europe"],
            countries=["United States", "United Kingdom"],
            languages=["en"],
            license_name="Apache-2.0",
            license_url="https://www.apache.org/licenses/LICENSE-2.0",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Kaggle invoice images; no automatic content download.",
            metadata={"kaggle_slug": "osamahosamabdellatif/high-quality-invoice-images-for-ocr"},
        ),
        candidate(
            dataset_id="kaggle:robikscube/textocr-text-extraction-from-images-dataset",
            dataset_name="TextOCR text extraction from images",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets/robikscube/textocr-text-extraction-from-images-dataset",
            modality="image",
            candidate_tasks=["document_ocr", "image_text_translation", "visual_question_answering"],
            regions=["North America", "Europe"],
            countries=["United States", "United Kingdom"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="training",
            source_quality="high",
            size_bytes=7_000_000_000,
            notes="Large TextOCR candidate; requires explicit download approval.",
            metadata={"kaggle_slug": "robikscube/textocr-text-extraction-from-images-dataset"},
        ),
        candidate(
            dataset_id="manual:FUNSD",
            dataset_name="FUNSD form understanding",
            source_catalog="manual",
            source_url="https://guillaumejaume.github.io/FUNSD/",
            modality="document_image",
            candidate_tasks=["document_ocr", "handwritten_note_transcription"],
            regions=["Europe"],
            countries=["France"],
            languages=["en"],
            license_name="CC-BY-NC-SA-4.0",
            license_url="https://creativecommons.org/licenses/by-nc-sa/4.0/",
            commercial_use_allowed=False,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="high",
            notes="Academic form-understanding dataset; non-commercial eval only by default.",
        ),
        candidate(
            dataset_id="manual:DocVQA",
            dataset_name="DocVQA",
            source_catalog="manual",
            source_url="https://www.docvqa.org/",
            modality="document_image",
            candidate_tasks=["document_ocr", "visual_question_answering"],
            regions=["Europe", "North America"],
            countries=["Spain", "United States"],
            languages=["en"],
            license_name="custom research terms",
            license_url="https://www.docvqa.org/datasets",
            commercial_use_allowed=False,
            redistribution_allowed=False,
            derivative_use_allowed=False,
            pii_risk="medium",
            intended_use="eval",
            source_quality="high",
            notes="Custom academic terms; keep rejected or manual-review only.",
        ),
        candidate(
            dataset_id="manual:FATURA",
            dataset_name="FATURA invoice dataset",
            source_catalog="manual",
            source_url="https://github.com/naiveHobo/InvoiceNet",
            modality="document_image",
            candidate_tasks=["invoice_extraction", "document_ocr"],
            regions=["Europe"],
            countries=["Turkey"],
            languages=["tr"],
            license_name="MIT",
            license_url="https://opensource.org/license/mit/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="training",
            source_quality="medium",
            notes="Invoice template dataset; verify source before download.",
        ),
        candidate(
            dataset_id="manual:XFUND",
            dataset_name="XFUND multilingual form understanding",
            source_catalog="manual",
            source_url="https://github.com/doc-analysis/XFUND",
            modality="document_image",
            candidate_tasks=["document_ocr", "image_text_translation"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Japan", "France", "United States"],
            languages=["zh", "ja", "es", "fr", "it", "de", "pt"],
            license_name="MIT",
            license_url="https://opensource.org/license/mit/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="training",
            source_quality="high",
            notes="Multilingual form understanding; useful for layout transfer.",
        ),
        candidate(
            dataset_id="manual:CORD",
            dataset_name="CORD receipt dataset",
            source_catalog="manual",
            source_url="https://github.com/clovaai/cord",
            modality="document_image",
            candidate_tasks=["receipt_extraction", "document_ocr"],
            regions=["Southeast Asia"],
            countries=["Indonesia", "Vietnam", "Singapore"],
            languages=["en", "id"],
            license_name="Apache-2.0",
            license_url="https://www.apache.org/licenses/LICENSE-2.0",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="training",
            source_quality="high",
            notes="Receipt extraction dataset with structured labels and SEA relevance.",
        ),
        # Accessibility image / VQA.
        candidate(
            dataset_id="manual:VizWiz-VQA",
            dataset_name="VizWiz VQA",
            source_catalog="manual",
            source_url="https://vizwiz.org/tasks-and-datasets/vqa/",
            modality="image",
            candidate_tasks=["image_accessibility_description", "visual_question_answering"],
            regions=["North America"],
            countries=["United States"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="high",
            notes="Accessibility VQA from blind users; inspect images for privacy before training.",
        ),
        candidate(
            dataset_id="manual:VizWiz-Captions",
            dataset_name="VizWiz Captions",
            source_catalog="manual",
            source_url="https://vizwiz.org/tasks-and-datasets/image-captioning/",
            modality="image",
            candidate_tasks=["image_accessibility_description"],
            regions=["North America"],
            countries=["United States"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="high",
            notes="Caption labels relevant to low-vision assistance.",
        ),
        candidate(
            dataset_id="huggingface:facebook/textvqa",
            dataset_name="TextVQA",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/facebook/textvqa",
            modality="image",
            candidate_tasks=["image_text_translation", "visual_question_answering"],
            regions=["North America", "Europe"],
            countries=["United States", "United Kingdom"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="training",
            source_quality="high",
            size_bytes=8_000_000_000,
            notes="Large image text VQA dataset; download requires explicit approval.",
            metadata={"hf_repo_id": "facebook/textvqa"},
        ),
        candidate(
            dataset_id="kaggle:ingbiodanielh/vizwiz",
            dataset_name="Kaggle VizWiz",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets/ingbiodanielh/vizwiz",
            modality="image",
            candidate_tasks=["image_accessibility_description", "visual_question_answering"],
            regions=["North America"],
            countries=["United States"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Kaggle mirror; keep metadata-only until reviewed.",
            metadata={"kaggle_slug": "ingbiodanielh/vizwiz"},
        ),
        candidate(
            dataset_id="kaggle:aishrules25/automatic-image-captioning-for-visually-impaired",
            dataset_name="Automatic image captioning for visually impaired",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets/aishrules25/automatic-image-captioning-for-visually-impaired",
            modality="image",
            candidate_tasks=["image_accessibility_description"],
            regions=["India"],
            countries=["India"],
            languages=["en"],
            license_name="CC0-1.0",
            license_url="https://creativecommons.org/publicdomain/zero/1.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="training",
            source_quality="medium",
            notes="India-focused accessibility captioning candidate.",
            metadata={
                "kaggle_slug": (
                    "aishrules25/automatic-image-captioning-for-visually-impaired"
                )
            },
        ),
        # ASR.
        candidate(
            dataset_id="huggingface:ai4bharat/IndicVoices",
            dataset_name="IndicVoices",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/ai4bharat/IndicVoices",
            modality="audio",
            candidate_tasks=["speech_to_text", "eval_only"],
            regions=["India"],
            countries=["India"],
            languages=["hi", "ta", "te", "bn", "mr"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="high",
            size_bytes=50_000_000_000,
            notes="Transcript audio dataset; Indian non-English ASR remains experimental for v1.",
            metadata={"hf_repo_id": "ai4bharat/IndicVoices"},
        ),
        candidate(
            dataset_id="huggingface:mozilla-foundation/common_voice_17_0",
            dataset_name="Mozilla Common Voice",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/mozilla-foundation/common_voice_17_0",
            modality="audio",
            candidate_tasks=["speech_to_text"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "Germany", "United States"],
            languages=["en", "hi", "de", "fr"],
            license_name="CC0-1.0",
            license_url="https://creativecommons.org/publicdomain/zero/1.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="training",
            source_quality="high",
            size_bytes=100_000_000_000,
            notes="Large ASR transcript dataset; no automatic download.",
            metadata={"hf_repo_id": "mozilla-foundation/common_voice_17_0"},
        ),
        candidate(
            dataset_id="huggingface:google/fleurs",
            dataset_name="FLEURS",
            source_catalog="huggingface",
            source_url="https://huggingface.co/datasets/google/fleurs",
            modality="audio",
            candidate_tasks=["speech_to_text"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Indonesia", "France", "United States"],
            languages=["en", "hi", "id", "fr"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="high",
            notes="Transcript ASR benchmark; good regional stress-test source.",
            metadata={"hf_repo_id": "google/fleurs"},
        ),
        candidate(
            dataset_id="kaggle:bengaliai-speech",
            dataset_name="BengaliAI speech",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/competitions/bengaliai-speech",
            modality="audio",
            candidate_tasks=["speech_to_text", "eval_only"],
            regions=["India"],
            countries=["India", "Bangladesh"],
            languages=["bn"],
            license_name="competition terms",
            license_url="https://www.kaggle.com/competitions/bengaliai-speech/rules",
            commercial_use_allowed=False,
            redistribution_allowed=False,
            derivative_use_allowed=False,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Competition terms; eval-only pending legal review.",
            metadata={"kaggle_slug": "bengaliai-speech"},
        ),
        candidate(
            dataset_id="kaggle:malaysian-asr",
            dataset_name="Malaysian ASR",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets",
            modality="audio",
            candidate_tasks=["speech_to_text"],
            regions=["Southeast Asia"],
            countries=["Malaysia"],
            languages=["ms", "en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Manual Kaggle lookup required; metadata seed only.",
            metadata={"kaggle_slug": "malaysian-asr"},
        ),
        candidate(
            dataset_id="kaggle:indian-languages-audio-dataset",
            dataset_name="Indian languages audio dataset",
            source_catalog="kaggle",
            source_url="https://www.kaggle.com/datasets",
            modality="audio",
            candidate_tasks=["speech_to_text", "eval_only"],
            regions=["India"],
            countries=["India"],
            languages=["hi", "ta", "te"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="medium",
            notes="Metadata seed for Indian ASR; inspect transcripts before training.",
            metadata={"kaggle_slug": "indian-languages-audio-dataset"},
        ),
        candidate(
            dataset_id="manual:ai4bharat-asr-benchmarks",
            dataset_name="AI4Bharat ASR benchmarks",
            source_catalog="manual",
            source_url="https://github.com/AI4Bharat",
            modality="audio",
            candidate_tasks=["speech_to_text", "eval_only"],
            regions=["India"],
            countries=["India"],
            languages=["hi", "ta", "te", "bn", "mr"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="medium",
            notes="ASR benchmark manifests; use for eval/regional stress only.",
        ),
        # Tabular / summarization / tool routing / eval.
        candidate(
            dataset_id="uci:bank-marketing",
            dataset_name="UCI Bank Marketing",
            source_catalog="uci_ml_repository",
            source_url="https://archive.ics.uci.edu/dataset/222/bank+marketing",
            modality="tabular",
            candidate_tasks=["tabular_reasoning", "eval_only"],
            regions=["Europe"],
            countries=["Portugal"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            contains_sensitive_data=True,
            intended_use="eval",
            source_quality="medium",
            notes="Financial marketing data with real individuals; eval-only.",
        ),
        candidate(
            dataset_id="uci:default-credit-card-clients",
            dataset_name="UCI Default of Credit Card Clients",
            source_catalog="uci_ml_repository",
            source_url="https://archive.ics.uci.edu/dataset/350/default+of+credit+card+clients",
            modality="tabular",
            candidate_tasks=["tabular_reasoning", "eval_only"],
            regions=["Southeast Asia"],
            countries=["Taiwan"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="high",
            contains_sensitive_data=True,
            intended_use="eval",
            source_quality="medium",
            notes="Real individual financial records; blocked unless redacted or opt-in.",
        ),
        candidate(
            dataset_id="uci:online-retail",
            dataset_name="UCI Online Retail",
            source_catalog="uci_ml_repository",
            source_url="https://archive.ics.uci.edu/dataset/352/online+retail",
            modality="tabular",
            candidate_tasks=["tabular_reasoning", "json_repair", "eval_only"],
            regions=["Europe"],
            countries=["United Kingdom"],
            languages=["en"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="eval",
            source_quality="high",
            notes="Retail transactions; eval-only for tabular reasoning and Excel tests.",
        ),
        candidate(
            dataset_id="aws:open-data-catalog",
            dataset_name="AWS Registry of Open Data catalog",
            source_catalog="aws_open_data_registry",
            source_url="https://registry.opendata.aws/",
            modality="mixed",
            candidate_tasks=["tool_routing", "eval_only"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "Germany", "United States"],
            languages=["en"],
            license_name="catalog metadata terms",
            license_url="https://registry.opendata.aws/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="medium",
            notes="Discovery catalog only; no runtime dependency or automatic dataset download.",
        ),
        candidate(
            dataset_id="google:bigquery-public-datasets-catalog",
            dataset_name="Google BigQuery public datasets catalog",
            source_catalog="google_public_datasets",
            source_url="https://cloud.google.com/bigquery/public-data",
            modality="mixed",
            candidate_tasks=["tool_routing", "eval_only"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "Germany", "United States"],
            languages=["en"],
            license_name="catalog metadata terms",
            license_url="https://cloud.google.com/terms/",
            commercial_use_allowed=True,
            redistribution_allowed=False,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="medium",
            notes="Manual/metadata import only; no runtime GCP dependency.",
        ),
        candidate(
            dataset_id="azure:open-datasets-catalog",
            dataset_name="Azure Open Datasets catalog",
            source_catalog="azure_open_datasets",
            source_url="https://learn.microsoft.com/en-us/azure/open-datasets/dataset-catalog",
            modality="mixed",
            candidate_tasks=["tool_routing", "eval_only"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "France", "United States"],
            languages=["en"],
            license_name="Microsoft Open Use of Data Agreement",
            license_url="https://learn.microsoft.com/en-us/legal/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="medium",
            notes="Catalog-level discovery only; no runtime Azure dependency.",
        ),
        candidate(
            dataset_id="europe:data-europa-catalog",
            dataset_name="European Data Portal catalog",
            source_catalog="european_data_portal",
            source_url="https://data.europa.eu/data/datasets",
            modality="mixed",
            candidate_tasks=["text_summarization", "eval_only"],
            regions=["Europe"],
            countries=["France", "Germany", "Netherlands"],
            languages=["en", "fr", "de", "nl"],
            license_name="CC-BY-4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="medium",
            notes="Aggregated EU metadata; publisher and licence must be preserved.",
            metadata={"publisher": "data.europa.eu", "publisher_license": "varies by source"},
        ),
        candidate(
            dataset_id="epo:ops-patent-data",
            dataset_name="EPO Open Patent Services manifest",
            source_catalog="epo",
            source_url="https://www.epo.org/en/searching-for-patents/data/web-services/ops",
            modality="text",
            candidate_tasks=["text_summarization", "eval_only"],
            regions=["Europe"],
            countries=["Germany", "France", "United Kingdom"],
            languages=["en", "fr", "de"],
            license_name="EPO OPS terms",
            license_url="https://www.epo.org/en/service-support/terms-use",
            commercial_use_allowed=False,
            redistribution_allowed=False,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="high",
            notes="Patent/technical summarization only; no elderly financial extraction use.",
            metadata={"ops_endpoint": "optional", "credential_required": "optional developer tool"},
        ),
        candidate(
            dataset_id="wikimedia:selected-wikipedia-dumps",
            dataset_name="Selected Wikipedia dumps",
            source_catalog="wikimedia",
            source_url="https://dumps.wikimedia.org/",
            modality="text",
            candidate_tasks=["wikipedia_summarization", "text_summarization"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Indonesia", "France", "United States"],
            languages=["en", "hi", "id", "fr", "de"],
            license_name="CC-BY-SA-4.0",
            license_url="https://creativecommons.org/licenses/by-sa/4.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="medium",
            intended_use="training",
            source_quality="high",
            size_bytes=20_000_000_000,
            notes="Selected dumps only; no full dump bundled in app runtime.",
        ),
        candidate(
            dataset_id="awesome:awesome-public-datasets-index",
            dataset_name="Awesome Public Datasets index",
            source_catalog="awesome_public_datasets",
            source_url="https://github.com/awesomedata/awesome-public-datasets",
            modality="mixed",
            candidate_tasks=["tool_routing", "eval_only"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "Germany", "United States"],
            languages=["en"],
            license_name="CC0-1.0",
            license_url="https://creativecommons.org/publicdomain/zero/1.0/",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="medium",
            notes="Discovery index only; individual datasets require separate approval.",
        ),
        candidate(
            dataset_id="google-dataset-search:manual-export",
            dataset_name="Google Dataset Search manual export",
            source_catalog="google_dataset_search",
            source_url="https://datasetsearch.research.google.com/",
            modality="mixed",
            candidate_tasks=["tool_routing", "eval_only"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "France", "United States"],
            languages=["en"],
            license_name="manual export terms",
            license_url="https://policies.google.com/terms",
            commercial_use_allowed=True,
            redistribution_allowed=False,
            derivative_use_allowed=True,
            pii_risk="low",
            intended_use="eval",
            source_quality="medium",
            notes="Browser/account-mediated discovery via local CSV/JSON export.",
        ),
        candidate(
            dataset_id="synthetic:local-lm-regional-documents",
            dataset_name="local-lm synthetic regional documents",
            source_catalog="synthetic",
            source_url="file:data/synthetic",
            modality="document_image",
            candidate_tasks=[
                "invoice_extraction",
                "receipt_extraction",
                "bill_extraction",
                "bank_statement_extraction",
                "document_ocr",
            ],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "France", "United States"],
            languages=["en", "hi", "fr"],
            license_name="Apache-2.0",
            license_url="https://www.apache.org/licenses/LICENSE-2.0",
            commercial_use_allowed=True,
            redistribution_allowed=True,
            derivative_use_allowed=True,
            pii_risk="none",
            intended_use="training",
            source_quality="high",
            local_path="data/synthetic",
            checksum=None,
            notes="Repo-generated synthetic data; safe for training after generation.",
            metadata_only=False,
        ),
        candidate(
            dataset_id="user-opt-in:redacted-local-documents",
            dataset_name="User opt-in redacted local documents",
            source_catalog="user_opt_in_redacted",
            source_url="file:data/raw/user_opt_in_redacted",
            modality="mixed",
            candidate_tasks=["document_ocr", "invoice_extraction", "bank_statement_extraction"],
            regions=["India", "Southeast Asia", "Europe", "North America"],
            countries=["India", "Singapore", "Germany", "United States"],
            languages=["en"],
            license_name="explicit user opt-in",
            license_url="file:data/raw/user_opt_in_redacted/LICENSE.md",
            commercial_use_allowed=False,
            redistribution_allowed=False,
            derivative_use_allowed=True,
            pii_risk="high",
            contains_sensitive_data=True,
            intended_use="eval",
            source_quality="medium",
            local_path="data/raw/user_opt_in_redacted",
            notes="Only redacted, explicit opt-in records; never uploaded.",
            redacted=True,
            explicit_user_opt_in=True,
        ),
    ]
    return dedupe_candidates(records)
